// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BxBxlInstagram: typeof import('~icons/bx/bxl-instagram')['default']
    BxBxlWhatsapp: typeof import('~icons/bx/bxl-whatsapp')['default']
    BxEnvelope: typeof import('~icons/bx/envelope')['default']
    HomeIndustry: typeof import('./../components/home/HomeIndustry.vue')['default']
    HuiDialog: typeof import('@headlessui/vue')['Dialog']
    HuiDialogOverlay: typeof import('@headlessui/vue')['DialogOverlay']
    HuiTransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    HuiTransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    PhEnvelopeSimpleOpenFill: typeof import('~icons/ph/envelope-simple-open-fill')['default']
    PhList: typeof import('~icons/ph/list')['default']
    PhListBold: typeof import('~icons/ph/list-bold')['default']
    PhListFill: typeof import('~icons/ph/list-fill')['default']
    PhMapPinFill: typeof import('~icons/ph/map-pin-fill')['default']
    PhPhoneFill: typeof import('~icons/ph/phone-fill')['default']
    PhX: typeof import('~icons/ph/x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./../components/global/TheFooter.vue')['default']
    TheHeader: typeof import('./../components/global/TheHeader.vue')['default']
    TheMobileNavigation: typeof import('./../components/global/TheMobileNavigation.vue')['default']
    TheSlideover: typeof import('./../components/ui/TheSlideover.vue')['default']
    TheSocialIcons: typeof import('./../components/global/TheSocialIcons.vue')['default']
  }
}

export {}
